In [1]:
import numpy as np
import pandas as pd

In [66]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
data_1 = pd.read_csv('ECG200_TRAIN.csv',delimiter= "  ", header = None)

C:\Users\Hp\AppData\Local\Temp\ipykernel_14244\2859132206.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data_1 = pd.read_csv('ECG200_TRAIN.csv',delimiter= "  ", header = None)


In [22]:
# d1 = data_1.iloc[:20]
# d2 = data_1.iloc[20:40]
# d3 = data_1.iloc[40:60]
# d4 = data_1.iloc[60:80]
# d5 = data_1.iloc[80:100]
# d1 = data_1.iloc[:33]
# d2 = data_1.iloc[33:66]
# d3 = data_1.iloc[67:100]

In [14]:
data_1 = data_1.sort_values(by=[0], ascending=True)

In [26]:
d1 = data_1.iloc[:31]
d2 = data_1.iloc[31:100]

In [45]:
f1 = d1.iloc[:10]
f2 = d2.iloc[:23]
fold_1 = pd.concat([f1, f2], axis=0)

In [46]:
f1 = d1.iloc[10:20]
f2 = d2.iloc[23:46]
fold_2 = pd.concat([f1, f2], axis=0)

In [47]:
f1 = d1.iloc[20:30]
f2 = d2.iloc[46:69]
fold_3 = pd.concat([f1, f2], axis=0)

In [58]:
train_1 = pd.concat([fold_1, fold_2], axis=0)
test_1 = fold_3
train_1_0 = train_1[0]
train_1 = train_1.drop([0], axis=1)
test_1_0 = test_1[0]
test_1 = test_1.drop([0], axis=1)


In [61]:
train_2 = pd.concat([fold_2, fold_3], axis=0)
test_2 = fold_1
train_2_0 = train_2[0]
train_2 = train_2.drop([0], axis=1)
test_2_0 = test_2[0]
test_2 = test_2.drop([0], axis=1)

In [67]:
train_3 = pd.concat([fold_1, fold_3], axis=0)
test_3 = fold_2
train_3_0 = train_3[0]
train_3 = train_3.drop([0], axis=1)
test_3_0 = test_3[0]
test_3 = test_3.drop([0], axis=1)

In [68]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(train_1, train_1_0)
pred = knn.predict(test_1)
 
print('WITH K = 1')
print('\n')
print(confusion_matrix(test_1_0, pred))
print('\n')
print(classification_report(test_1_0, pred))
 
 
# NOW WITH K = 15
knn = KNeighborsClassifier(n_neighbors = 15)
 
knn.fit(train_1, train_1_0)
pred = knn.predict(test_1)
 
print('WITH K = 15')
print('\n')
print(confusion_matrix(test_1_0, pred))
print('\n')
print(classification_report(test_1_0, pred))

WITH K = 1


[[ 6  4]
 [ 1 22]]


              precision    recall  f1-score   support

        -1.0       0.86      0.60      0.71        10
         1.0       0.85      0.96      0.90        23

    accuracy                           0.85        33
   macro avg       0.85      0.78      0.80        33
weighted avg       0.85      0.85      0.84        33

WITH K = 15


[[ 7  3]
 [ 2 21]]


              precision    recall  f1-score   support

        -1.0       0.78      0.70      0.74        10
         1.0       0.88      0.91      0.89        23

    accuracy                           0.85        33
   macro avg       0.83      0.81      0.82        33
weighted avg       0.85      0.85      0.85        33



In [69]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(train_2, train_2_0)
pred = knn.predict(test_2)
 
print('WITH K = 1')
print('\n')
print(confusion_matrix(test_2_0, pred))
print('\n')
print(classification_report(test_2_0, pred))
 
 
# NOW WITH K = 15
knn = KNeighborsClassifier(n_neighbors = 15)
 
knn.fit(train_2, train_2_0)
pred = knn.predict(test_2)
 
print('WITH K = 15')
print('\n')
print(confusion_matrix(test_2_0, pred))
print('\n')
print(classification_report(test_2_0, pred))

WITH K = 1


[[ 9  1]
 [ 1 22]]


              precision    recall  f1-score   support

        -1.0       0.90      0.90      0.90        10
         1.0       0.96      0.96      0.96        23

    accuracy                           0.94        33
   macro avg       0.93      0.93      0.93        33
weighted avg       0.94      0.94      0.94        33

WITH K = 15


[[ 4  6]
 [ 5 18]]


              precision    recall  f1-score   support

        -1.0       0.44      0.40      0.42        10
         1.0       0.75      0.78      0.77        23

    accuracy                           0.67        33
   macro avg       0.60      0.59      0.59        33
weighted avg       0.66      0.67      0.66        33



In [70]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(train_3, train_3_0)
pred = knn.predict(test_3)
 
print('WITH K = 1')
print('\n')
print(confusion_matrix(test_3_0, pred))
print('\n')
print(classification_report(test_3_0, pred))
 
 
# NOW WITH K = 15
knn = KNeighborsClassifier(n_neighbors = 15)
 
knn.fit(train_3, train_3_0)
pred = knn.predict(test_3)
 
print('WITH K = 15')
print('\n')
print(confusion_matrix(test_3_0, pred))
print('\n')
print(classification_report(test_3_0, pred))

WITH K = 1


[[ 8  2]
 [ 1 22]]


              precision    recall  f1-score   support

        -1.0       0.89      0.80      0.84        10
         1.0       0.92      0.96      0.94        23

    accuracy                           0.91        33
   macro avg       0.90      0.88      0.89        33
weighted avg       0.91      0.91      0.91        33

WITH K = 15


[[ 4  6]
 [ 2 21]]


              precision    recall  f1-score   support

        -1.0       0.67      0.40      0.50        10
         1.0       0.78      0.91      0.84        23

    accuracy                           0.76        33
   macro avg       0.72      0.66      0.67        33
weighted avg       0.74      0.76      0.74        33



In [100]:
e1 = data_1.iloc[0:31]
e2 = data_1.iloc[31:100]

In [101]:
e1_0 = e1[0]
e1 = e1.drop([0], axis=1)
e2_0 = e2[0]
e2 = e2.drop([0], axis=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
 
scaler = StandardScaler()
 
scaler.fit(data_1.drop('TARGET CLASS', axis = 1))
scaled_features = scaler.transform(data_1.drop(0, axis = 1))
 
df_feat = pd.DataFrame(scaled_features, columns = data_1.columns[:-1])
df_feat.head()

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(e2, e2_0)
pred = knn.predict(e1)
 
print('WITH K = 1')
print('\n')
print(confusion_matrix(e1_0, pred))
print('\n')
print(classification_report(e1_0, pred))
 
 
# NOW WITH K = 15
knn = KNeighborsClassifier(n_neighbors = 15)
 
knn.fit(e2, e2_0)
pred = knn.predict(e1)
 
print('WITH K = 15')
print('\n')
print(confusion_matrix(e1_0, pred))
print('\n')
print(classification_report(e1_0, pred))